### ISSUE TITLE
Slide in down

### ISSUE THREAD

**Issue by mozzymoz** [geoffgraham/animate.scss#16]
Hi there,
I used your mixin for the slideindown animation, however what CSS do I have to set for the element to start from a 0 height?

**Comment by geoffgraham** [comment]
Hmm, I'm not sure how that would work well with this specific animation. The animation is supposed to bring an element onto the page from an offscreen position. By default, the animation translates the element vertically from -2000px.

Your best bet might be to edit the animation altogether so that it starts from a 0 position then translates from there...but then it's technically not a slide in effect anymore. :)

Something like:

`0% {opacity: 0; transform: translateY(0);}
100% {transform: translateY(2000px);} /* Or whatever position you want it to land at. */`

Cheers!
