### ISSUE TITLE
Remove the normal .css file from root

### ISSUE THREAD

**Issue by iDuuck** [geoffgraham/animate.scss#42]
If I am using `gulp-sass` and adding the path `./bower_components/animatewithsass` to the `includePaths` and then requiring the animate.scss via `@import 'animate';` I get the following error: 

```
Error: It's not clear which file to import for '@import "animate"'.
       Candidates:
         animate.scss
         animate.css
       Please delete or rename all but one of these files.
        on line 13 of stdin
>> @import 'animate';
```

To be clear, it should be possible to just use `@import 'animate.scss';` here, but this is against my `.scss-lint.yml` linters. (That's not the reason I want it to be removed, but why would someone install animate.scss, when he really wants the css. So the `.css` file is unncessary, right?

**Comment by geoffgraham** [comment]
Hey there! That's a good question. I personally believe that the CSS file is the point of the project, as it is with the Animate.css project. The extra benefits that come along with using Sass to compile that file (namely mixins and imports) makes it that much deeper.

But that's just my thought. The point your making is interesting because build tools are such a big part of the development process. It might be worth adding another level of directories that separate CSS and SCSS.
